{% set version = "1.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-countrycode
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/countrycode_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/countrycode/countrycode_{{ version }}.tar.gz
  sha256: 99dfe7652c1e631b9e0f8fac0b0163e7a3fdde8476498555d553e0d1c5fdccc4

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('countrycode')"           # [not win]
    - "\"%R%\" -e \"library('countrycode')\""  # [win]

about:
  home: https://github.com/vincentarelbundock/countrycode
  license: GPL-3.0-only
  summary: Standardize country names, convert them into one of eleven coding schemes, convert between coding schemes, and assign region descriptors.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
