appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: RP4+AmjQtFijemEXQ/rIigJyZLKj3vPwOFvgLakrT6KKo5fVP2HDQcGfgLIQbCyZz1RoIIfguH17BW9nT6kO1kUY7A4K869wR4GMrSCdUDtGHEwzSBvyW8zwHEY4jXCnpsW+mLUb1HkbDGQbunJKs4gN6wVaz5w6ZcMNUywfYIWsu7Vs1MlBt5KIgTWwqJIWjQ1/o1DxLruNsfnabnOA/rgdCnAcdViaQ4nOhNlumpQ35Jouyx+V6HZC2Prhr6uzam8ci9Nn6wewN2up0RUjrBGc0uxyteTLqrbW7Adb7/DUN4d6lu0TZR7L6l6X6ePg1+t0AOv8003Vl4UHbqU70R5/4mGGd6HiYsm7K/w67cNqelyI3/Igxbe5jIVhNbL0Svppimy+gmW1VzM7yDp/tUKHgjWM79QEulKmQcXVt1wtCiuuQA/AUS3FIbx+jvHhj80/zJ6hPS7lpEA0vkz0/R86+aRSMxZRL42TA8XR8zLGrDcCzlYjOMlF2q53BInnUxCIeS4IPH+0NQ2eQoIsheyq/31AaHX+8LobgqHPf0t5wslrFbRDfu8p1b0vP7uLthUu54ukN/R/pOeQ6TivW1zm5yPB4GFiY3EadAnNYdEQYfhPQ6g1uWA8W7zTax/y/PEvxbMQvEBqYexfiAWnnsTL2ynD5RR8BFC5xcv1MCc=
