travis:
  secure:
    BINSTAR_TOKEN: aJFXAkgm/syxpG/Wl4BegpXDYqriEycazQHZWlaxf9RTC7oHrWbz7E/BGMOjXctleleZg2da1huOEInhkUIt3fzbUXITcrGRJbDFsm83MQOMlTssdSzwYs0QBaaO225l26Gt/8Y68NFe3UQIY/MyTGEN3RJAFt2v671ud6DJouR74/UVm1W8R8/gAJK7SfOSbqN6RWteWLsNcCZLFha7shPfS6B83oIBu4sneoNh8n557OAnF3/WqnoeSx2KW0lXNyqGxHKk4xceHlP4UFhMFYyeI6LFR61qgvQ1GXe6WE5qzVQUDiGkZXYpvSz3ScavUU9W0AOsmguEC99fzMsvzZI/FeKyLsjKMjIrkqiKBSm35majyUE8mnOhC56imbAtRjhfZy52aAiUMNfprQmAyulHNavDMauo7Z6n6syxbKSZxr+TCKBkk65geMKVBU37P7FBwRn10Dp+RPehFBbX/Xy9qWpB2RKPLi7jzPPMcz+CA0B0t8CsN+V0jROn7WXeng4Aj8UQ2HuYFey/OpRMm5ZhIc0i4ZDKmHxgz4z2SM1gZCb+tZ7Krm5NoiiHnPULstUr5NYVARMg0ZFchsnZMluQnAAOVyakMpKZwK6a3B3GkdvtxoFzqx6bcG4q37KDsVkQU1cGhZ17uDxhSrMnGDXKjAxAvHOKeo3DDkuiJQI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
